/** possible run lifecycle states for an end-to-end hydra run. */
export type RunStatus =
	| "decomposing"
	| "researching"
	| "debating"
	| "synthesizing"
	| "complete"
	| "error";

/** phase names for individual agent runs. */
export type AgentPhase = "decompose" | "research" | "debate" | "synthesis";

/** status for a single agent execution lifecycle. */
export type AgentRunStatus = "queued" | "running" | "complete" | "error";

/** configuration used to identify a persona and its style contract. */
export interface PersonaConfig {
	id: string;
	name: string;
	description: string;
	methodology: string;
}

/** normalized search result returned from any search provider. */
export interface SearchResult {
	title: string;
	url: string;
	text: string;
	published: string | null;
}

/** supported web search providers. */
export type SearchProvider = "synthetic" | "exa" | "brave";

/** configuration for web search routing and provider credentials. */
export interface SearchConfig {
	provider: SearchProvider;
	syntheticApiKey: string;
	exaApiKey: string;
	braveApiKey: string;
}

/** single decomposition assignment routed to a persona. */
export interface DecomposedAssignment {
	persona: string;
	subQuestion: string;
	methodology: string;
}

/** output generated by one persona in any processing phase. */
export interface AgentOutput {
	persona: string;
	output: string;
	searchQueries: string[];
}

/** complete process configuration consumed by runtime and persistence layers. */
export interface Config {
	apiKey?: string;
	syntheticApiKey?: string;
	searchProvider: SearchProvider;
	exaApiKey?: string;
	braveApiKey?: string;
	baseUrl: string;
	model: string;
	orchestratorModel?: string;
	researchModel?: string;
	defaultAgentCount: number;
	maxConcurrency: number;
	debateRounds: number;
	searchEnabled: boolean;
	customPersonasOnly: boolean;
}

/** partial configuration loaded from user-provided files or overrides. */
export type ConfigFile = Partial<Config>;

/** canonical in-code config type alias for backwards compatibility. */
export type HydraConfig = Config;

/** canonical config file alias used by persistence and cli entry points. */
export type HydraConfigFile = ConfigFile;

/** persisted metadata for a top-level run. */
export interface RunRecord {
	id: string;
	query: string;
	agentCount: number;
	status: RunStatus;
	brief: string | null;
	error: string | null;
	pipelineState: string | null;
	totalPromptTokens: number;
	totalCompletionTokens: number;
	createdAt: number;
	completedAt: number | null;
	elapsedMs: number | null;
}

/** persisted metadata for one agent run. */
export interface AgentRunRecord {
	id: string;
	runId: string;
	phase: AgentPhase;
	persona: string;
	systemPrompt: string;
	messages: string;
	output: string;
	searchQueries: string;
	status: AgentRunStatus;
	promptTokens: number;
	completionTokens: number;
	startedAt: number;
	completedAt: number | null;
}

/** minimal agent state payload emitted for progress/update events. */
export interface AgentRunState {
	runId: string;
	phase: AgentPhase;
	persona: string;
	status: AgentRunStatus;
	startedAt: number;
	completedAt: number | null;
	promptTokens: number;
	completionTokens: number;
	output: string;
}

/** emitted events from pipeline execution for cli progress and persistence. */
export type PipelineEvent =
	| {
			type: "run-created";
			runId: string;
			query: string;
			agentCount: number;
			timestamp: number;
	  }
	| {
			type: "run-status-changed";
			runId: string;
			status: RunStatus;
			timestamp: number;
	  }
	| {
			type: "agent-progress";
			runId: string;
			phase: AgentPhase;
			completedAgents: number;
			totalAgents: number;
			timestamp: number;
	  }
	| {
			type: "agent-complete";
			runId: string;
			agentRunId: string;
			persona: string;
			phase: AgentPhase;
			state: AgentRunState;
			timestamp: number;
	  }
	| {
			type: "run-complete";
			runId: string;
			elapsedMs: number;
			totalPromptTokens: number;
			totalCompletionTokens: number;
			timestamp: number;
	  };
